//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSoro_AragonSkills.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas
    {
        public int idPelicula { get; set; }
        public string nombre { get; set; }
        public string rating { get; set; }
        public string posicion { get; set; }
        public string reparto { get; set; }
        public string año { get; set; }
        public string url_foto { get; set; }
        public string url_imbd { get; set; }
    }
}
